# Generated by Django 2.1 on 2018-08-25 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('freeEntry', models.BooleanField()),
                ('bere', models.BooleanField()),
                ('mangiare', models.BooleanField()),
                ('benessere', models.BooleanField()),
                ('dormire', models.BooleanField()),
                ('goloso', models.BooleanField()),
                ('libri', models.BooleanField()),
                ('romantico', models.BooleanField()),
                ('museo', models.BooleanField()),
                ('spiaggia', models.BooleanField()),
                ('teatro', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profession', models.CharField(blank=True, max_length=40)),
                ('empathy', models.FloatField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('angry', 1), ('joyful', 2), ('sad', 3)], max_length=1)),
                ('companionship', models.CharField(choices=[('withFriends', 1), ('alone', 2)], max_length=1)),
                ('rating', models.IntegerField()),
                ('placeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommender.Place')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommender.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('userId', 'mood', 'companionship', 'placeId')},
        ),
    ]
